Add JS as a target for kmp-nativecoroutines-core
rickclephas/KMP-NativeCoroutines pull request #48
Opened 2022-02-22 20:50 UTC by ankushg

Part of https://github.com/rickclephas/KMP-NativeCoroutines/issues/17 and https://github.com/rickclephas/KMP-NativeCoroutines/pull/43

Doesn't add update any of KSP, but implements all `expect`s and gets tests passing for JS 😄

2022-02-22 21:10 UTC, ankushg commented
Not sure if you want to merge this individually or wait until we add the logic to KSP

2022-02-22 21:11 UTC, ankushg commented
@rickclephas Not sure if you want to merge this individually or wait until we add the logic to KSP

IMO merging it now makes sense so we can make sure things don't drift too much as other changes get merged

2022-02-23 17:00 UTC, rickclephas requested changes

2022-02-23 18:34 UTC, ankushg commented on kmp-nativecoroutines-core/src/jsTest/kotlin/com/rickclephas/kmp/nativecoroutines/RunTestJs.kt
> +    coroutineContext[Job]?.children?.forEach { it.join() }
Done (with the typecheck in `nativeCoroutinesMain`)

2022-02-23 18:41 UTC, rickclephas approved these changes

2022-02-23 18:57 UTC, rickclephas requested changes
Hmm looks like the coroutines-test classes aren't working as expected on JS 🤔

2022-02-23 20:12 UTC, ankushg commented
> Hmm looks like the coroutines-test classes aren't working as expected on JS 🤔

Hmm it was green before switching JS from `coroutineContext[Job]?.children?.forEach { it.join() }` to `runCurrent`

2022-03-03 00:07 UTC, ankushg commented
@rickclephas I figured it out! `runCurrent` runs the tasks that are pending **for the current virtual timestep**, but doesn't run any tasks that would be running in a future time step

What we really want to do is run **all** pending tasks until there are no more tasks to run. [`advanceUntilIdle` looks like it's designed to do that](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/advance-until-idle.html) 😄 

Replacing `runCurrent()` with `advanceUntilIdle()` fixes the JS tests

2022-03-03 17:38 UTC, rickclephas approved these changes

2022-03-04 18:18 UTC, merged